
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibsarezwhabbbbirdbnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlic2FyZXp3aGFiYmJiaXJkYm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyOTM5OTUsImV4cCI6MjA1Mjg2OTk5NX0.cgxPNr3VVm-3XO87PtaEjJfGH_FKW_cCmjPbMOGL9SU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'x-app-version': '1.0.0',
      },
    },
  }
);
